name: tag and release

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        id: autotag
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: package
          tag_prefix: "v"
          commit_message_template: ""
      - if: ${{steps.autotag.outputs.tagname}}
        run: gh release create ${{steps.autotag.outputs.tagname}} -R ${{github.repository}} --generate-notes -t "Release ${{steps.autotag.outputs.tagname}}"
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
