name: tag and release

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Tag current version"
        id: autotag
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: package
          tag_prefix: "v"
      - name: "Build changelog"
        if: ${{ steps.autotag.outputs.tagname }}
        id: changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create release"
        if: ${{ steps.autotag.outputs.tagname }}
        uses: softprops/action-gh-release@1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
